# Generated by Django 3.1.6 on 2021-04-16 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('cur', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=3, unique=True)),
                ('buy', models.DecimalField(decimal_places=3, max_digits=8)),
                ('buy_status', models.IntegerField()),
                ('sell', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sell_status', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
