# Generated by Django 3.1.6 on 2021-03-01 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('currency', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('buy', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buy_status', models.IntegerField(max_length=1)),
                ('sell', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sell_status', models.IntegerField(max_length=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
