# Generated by Django 3.1.6 on 2021-03-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='buy_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='sell_status',
            field=models.IntegerField(),
        ),
    ]
