# Generated by Django 3.1.6 on 2021-03-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0002_auto_20210301_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='cur_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
