# Generated by Django 3.1.6 on 2021-04-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0004_auto_20210301_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='cur_id',
            new_name='cur',
        ),
    ]
