language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
env:
  - export DJANGO_SETTINGS_MODULE="LMS.settings"
# command to run tests
script:
  - pytest --flake8

