# Generated by Django 3.1.6 on 2021-02-09 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('teacher', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=30)),
                ('group_name', models.CharField(max_length=20, unique=True, verbose_name='Group')),
                ('students', models.ManyToManyField(to='academy.Student')),
                ('teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.lecturer')),
            ],
        ),
    ]
