# Generated by Django 3.1.6 on 2021-02-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_remove_student_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(to='academy.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to='academy.Student', verbose_name='Students'),
        ),
    ]
