# Generated by Django 3.1.6 on 2021-02-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20210209_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='groups',
        ),
    ]
