# Generated by Django 3.1.6 on 2021-02-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_remove_student_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='teacher',
            new_name='teacher_id',
        ),
    ]
