# Generated by Django 3.1.6 on 2021-03-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_auto_20210209_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='photo/default.png', upload_to='photo/'),
        ),
    ]
