# Generated by Django 3.1.6 on 2021-02-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='method',
            field=models.CharField(max_length=10, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='path',
            field=models.CharField(max_length=100, verbose_name='URL'),
        ),
    ]
