# Generated by Django 3.1.6 on 2021-02-18 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20210218_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecord',
            name='access_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
